const places=[
    {
        img:'https://images.pexels.com/photos/208745/pexels-photo-208745.jpeg?auto=compress&cs=tinysrgb&w=400',
        placeName:'Paris'
    },
    {
        img:'https://images.pexels.com/photos/533769/pexels-photo-533769.jpeg?auto=compress&cs=tinysrgb&w=400',
        placeName:'Marseille'
    },
    {
        img:'https://images.pexels.com/photos/417054/pexels-photo-417054.jpeg?auto=compress&cs=tinysrgb&w=400',
        placeName:'Lyon'
    },
    {
        img:'https://images.pexels.com/photos/257433/pexels-photo-257433.jpeg?auto=compress&cs=tinysrgb&w=400',
        placeName:'Toulouse'
    },
    {
        img:'https://images.pexels.com/photos/532580/pexels-photo-532580.jpeg?auto=compress&cs=tinysrgb&w=400',
        placeName:'Nice'
    },
    {
        img:'https://images.pexels.com/photos/610533/pexels-photo-610533.jpeg?auto=compress&cs=tinysrgb&w=400',
        placeName:'Nantes'
    },
    {
        img:'https://images.pexels.com/photos/2885919/pexels-photo-2885919.jpeg?auto=compress&cs=tinysrgb&w=400',
        placeName:'Montpellier'
    },
    {
        img:'https://images.pexels.com/photos/3201921/pexels-photo-3201921.jpeg?auto=compress&cs=tinysrgb&w=400',
        placeName:'Bordeaux'
    }
]

module.exports=places;